spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/lizavetamuromskaya

    username: lizavetamuromskaya
    password: tedigo72
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  port: 8081
  spring:
    resources:
      add-mappings=true:

logging:
  file: "logs/app.log"
